module.exports = {
  generatePrice: (max, min) =>
    Math.floor((Math.random() * (max - min) + min) * 100) / 100,

  generateDescription: (name, type) =>
    `${name} is one of the best ${type} (<- This here might sound silly hehe). This text is totally not automatically generated by the way. Should've probably thought more about what sort of description to provide, but was way too lazy for that. Nobody is going to read this anyway so only two variables are unique(-ish). I need more coffee...`,

  getRandomValue: (data) => data[Math.floor(Math.random() * data.length)],

  isRequiredFile: (path) => {
    return path.endsWith('.txt') || path.endsWith('.json');
  },

  getFileType: (path) => {
    if (path.endsWith('.txt')) return 'txt';
    if (path.endsWith('.json')) return 'json';
    return console.error(
      'Unsuported file type. Only .txt and .json can be detected.'
    );
  },
};
